package model

import "time"

// PreMarketDecision records the final go/no-go decision for a signal before market open.
// Generated by the pre-market finalization pipeline (TradingAgents validation).
type PreMarketDecision struct {
	ID           uint      `gorm:"primaryKey" json:"id"`
	UserID       uint      `gorm:"index" json:"userId"`
	RunID        uint      `gorm:"index" json:"runId"`
	SignalID     uint      `gorm:"index" json:"signalId"`
	TradeDate    string    `gorm:"size:10;index" json:"tradeDate"`    // execution date (T+1)
	StockCode    string    `gorm:"size:10" json:"stockCode"`
	StockName    string    `gorm:"size:50" json:"stockName"`

	// Decision
	Status       string    `gorm:"size:15;default:pending" json:"status"` // pending / confirmed / rejected / modified
	FinalAction  string    `gorm:"size:10" json:"finalAction"`            // final action type (may differ from signal)
	FinalPrice   float64   `gorm:"type:numeric(12,4)" json:"finalPrice"`
	FinalQty     int       `json:"finalQty"`
	FinalAmount  float64   `gorm:"type:numeric(16,2)" json:"finalAmount"`
	Confidence   float64   `gorm:"type:numeric(5,2)" json:"confidence"`   // TA confidence 0-100

	// Order price suggestions
	SuggestedPremium float64 `gorm:"type:numeric(5,2);default:0" json:"suggestedPremium"`
	OrderPrice       float64 `gorm:"type:numeric(12,4);default:0" json:"orderPrice"`
	OrderPriceLimit  float64 `gorm:"type:numeric(12,4);default:0" json:"orderPriceLimit"`
	SuggestedQty     int     `gorm:"default:0" json:"suggestedQty"`

	// Pre-market context
	OpenPrice     float64 `gorm:"type:numeric(12,4);default:0" json:"openPrice"`
	OpenDeviation float64 `gorm:"type:numeric(6,2);default:0" json:"openDeviation"`
	DecisionRule  string  `gorm:"size:50" json:"decisionRule"`

	// Source
	Source       string    `gorm:"size:20;default:rule_based" json:"source"` // rule_based / ta_agent / manual

	// TradingAgents output
	TAReasoning  string    `gorm:"type:text" json:"taReasoning"`            // full TA reasoning chain
	TADebateJSON string    `gorm:"type:text" json:"taDebateJson"`           // JSON dump of TA debate history

	// Notification
	NotificationSent   bool   `json:"notificationSent"`
	NotificationChannel string `gorm:"size:30" json:"notificationChannel"` // channel that sent the notification

	// Reason
	Reason       string    `gorm:"type:text" json:"reason"`                 // human-readable decision rationale

	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

func (PreMarketDecision) TableName() string { return "pre_market_decisions" }
